camptocamp/bridge-style

bridgestyle/arcgis/togeostyler.py
[GEO-4768](https://jira.camptocamp.com/browse/GEO-4768)
=> Fix rotation sign

bridgestyle/arcgis/togeostyler.py
https://jira.camptocamp.com/browse/GEO-4831
https://jira.camptocamp.com/browse/GEO-4832
=> Improve symbol support

bridgestyle/arcgis/togeostyler.py, bridgestyle/sld/fromgeostyler.py
https://jira.camptocamp.com/browse/GEO-4833
=> Add support for null value comparison

bridgestyle/arcgis/togeostyler.py
[GEO-5209](https://jira.camptocamp.com/browse/GEO-5209)
=> Specify label grouping condition for polygons

bridgestyle/arcgis/togeostyler.py
[GEO-5812](https://jira.camptocamp.com/browse/GEO-5812)
=> Add support for GraduatedSymbol

bridgestyle/arcgis/togeostyler.py
[GEO-5814](https://jira.camptocamp.com/browse/GEO-5814)
=> Add support for rotation of GraduatedSymbol

bridgestyle/arcgis/expressions.py
[GEO-5919](https://jira.camptocamp.com/browse/GEO-5919)
Labels: Add support for "AND" and ">" in where clause
=> Extend where clause support in labels

bridgestyle/arcgis/togeostyler.py
[GEO-5921](https://jira.camptocamp.com/browse/GEO-5921)
If single symbol have an entry for the label in ArcGIS, show a text in the legend item
=> Add label for single symbol in legend

bridgestyle/arcgis/togeostyler.py
[GEO-5939](https://jira.camptocamp.com/browse/GEO-5939)
Ignore group with no class instead of throwing an error
=> Support group with no classes

bridgestyle/arcgis/togeostyler.py
[GEO-5814](https://jira.camptocamp.com/browse/GEO-5814)
=> Fix rotation angle in Arcade expression

bridgestyle/arcgis/togeostyler.py
[GEO-5861](https://jira.camptocamp.com/browse/GEO-5861)
=> Add check for maplex properties for point label placement

bridgestyle/arcgis/togeostyler.py, bridgestyle/arcgis/wkt_geometries.py, bridgestyle/sld/fromgeostyler.py
[GEO-5958](https://jira.camptocamp.com/browse/GEO-5958)
Add support for custom geometries in symbology (polygons only)
=> Add support for WKT symbology (polygons)

bridgestyle/arcgis/togeostyler.py
=> Support offset on CIMCharacterMarker

bridgestyle/arcgis/togeostyler.py, bridgestyle/arcgis/wkt_geometries.py, bridgestyle/sld/fromgeostyler.py
Add support for line geometries along polygon outline and polygon fill with character marker
[GEO-5958](https://jira.camptocamp.com/browse/GEO-5958)
=> Enhance support for polygon outline and fill

bridgestyle/sld/fromgeostyler.py
=> GEO-6217 Remove special characteres from the title

bridgestyle/arcgis/togeostyler.py, bridgestyle/sld/fromgeostyler.py
[GEO-5958](https://jira.camptocamp.com/browse/GEO-5958)
=> Improve support for polygon fill with marker

bridgestyle/arcgis/togeostyler.py, bridgestyle/mapserver/fromgeostyler.py, bridgestyle/qgis/togeostyler.py, bridgestyle/sld/fromgeostyler.py
GEO-6208
I've to recalculate the size of the marker because to show the full "dash" pattern, we can't  rely on separation + width.
=> HatchFill show dashed lines

bridgestyle/sld/fromgeostyler.py
For GEO-6217
I forget about this part of the ticket.
Now, we have a technical name (without special characters except underscore) and a human readable name. As the style name/title .
I'll merge directly, please post-merge review.
=> Rules: Use technical name and add title

bridgestyle/arcgis/togeostyler.py
=> Fix simple filter, keep improved or conditions

bridgestyle/arcgis/togeostyler.py, bridgestyle/sld/fromgeostyler.py
=> Add support for marker symbol at end of lines

bridgestyle/arcgis/togeostyler.py
- To be coherent, line and dash-pattern lines must have the same size treatment. Empirically, it looks that raw-sepration * 2 is the best size.
- Handle dash symbol without dash pattern.
- Add comments on rotation that crop lines (isze-box line are rotated, not the whole fill line). Keep rotating with symbols.
=> Fix tilted lines for fill.

bridgestyle/arcgis/togeostyler.py, bridgestyle/arcgis/wkt_geometries.py
=> Add support for curveRings in polygon fill

bridgestyle/arcgis/togeostyler.py
=> Add support for scale dependent symbols

bridgestyle/arcgis/constants.py, bridgestyle/arcgis/togeostyler.py
=> Add support for symbol at start of line

bridgestyle/arcgis/togeostyler.py
=> Use filter also for alternate symbols

bridgestyle/arcgis/togeostyler.py
=> Take into account extremityPlacement option

bridgestyle/arcgis/togeostyler.py
Initial implementation was actually correct
GEO-7273
=> Swap min and max scale

bridgestyle/arcgis/togeostyler.py
=> Add offset effect
